### ISSUE TITLE
Forum button in menu

### ISSUE THREAD

**Issue by dtu-compute** [dtu-compute/course-website#25]
that opens the Askbot for that particular course.

**Comment by iainbryson** [comment]
To be clear :you want to add the askbot-docker container into the mix with the other enote pieces (stackedit, course, etc..)? And then link up to the webservice in that container via the header in the course Web site?

**Comment by dtu-compute** [comment]
Yes, exactly =)

Each course will have their own

https://github.com/dtu-compute/docker-askbot

which is accessed by https://01005.compute.dtu.dk/askbot for 01005. In my reverse proxy I had a PoC of that.

Askbot have its own CAS login and a `users.yaml` for white listing which users are allowed to login.

So the Forum button in the menu should just link to https://01005.compute.dtu.dk/askbot for 01005.

**Comment by iainbryson** [comment]
How does askbot get configured for its course?  Where does it store its config state?  Or are these open questions for me to solve?

**Comment by dtu-compute** [comment]
[`config.sh`](https://github.com/dtu-compute/docker-askbot/blob/devel/config.sh) configures the specifics for the course.

Askbot uses SQlite, so each container will a volume which will be backed up.

`users.yaml` is also unique for each course. [`mycas.py`](https://github.com/dtu-compute/docker-askbot/blob/devel/mycas.py) should probably be modified at some point, so it uses the existing users file from the course.

**Comment by iainbryson** [comment]
So I’ll use askbot-docker as the container, and somehow pass in the details about which course it is?  For the course Web site this is governed by an environment variable for the container.

**Comment by dtu-compute** [comment]
Good point. I can update it tomorrow, if you don't do it =) It should only be `config.sh` that needs to be updated from what I can tell.

**Comment by iainbryson** [comment]
For reference, this is how it works for the course website:

```
  course-website-01005:
    environment:
      COURSE_NAME: "01005"
      RAILS_ENV: 'production'
    build: ./components/course-website
    volumes:
      - /root/vol-course-website-01005-public:/data/course-website-public
#      - /root/vol-filemanager:/filemanager
      - ./components/filemanager:/filemanager
      - ./components/dtu-data:/dtu-data
      - ./components/dtu-core:/dtu-core
    links:
      - couchdb:db
    expose:
      - "3000"
    networks:
      - nettest
```

So if you consume `COURSE_NAME` then it’ll work the same way in both places.
