### ISSUE TITLE
Generate random keys when building container

### ISSUE THREAD

**Issue by dtu-compute** [dtu-compute/course-website#42]
From my understanding these keys are used for signing cookies. If so, it would be fine with me, if new are generated at each Docker build. Or when starting the container is also fine.

https://github.com/dtu-compute/course-website/blob/devel/config/secrets.yml

**Comment by dtu-compute** [comment]
Can https://github.com/dtu-compute/course-website/blob/devel/config/secrets.yml then be deleted?

**Comment by dtu-compute** [comment]
Or if the `secrets.yml` is required, can the following then be removed?
```
development:
  secret_key_base: 87ef4fa7272f5811fe27e02201403953b2ea6609cb2c0883357dae8c54dd7efc6982254031ba5f30e52e166443784929ce2b965da42869cf2572c54e77071aeb

test:
  secret_key_base: 6014c9f51feae9ade8eb0d46395e08612406b563999c376e5f90ad35262d67e84a1443bc74606c19513c6171b19ee67b05287ea96297f5decc0964183e86c356
```
